spec/factories/tag_layout_template_factories.rb, spec/features/creating_a_tag_plate_spec.rb
Adds tests to make sure:
1) We support tags in row and column format
2) We support limiting tag layout templates
No code changes were required.
=> Ss666👿 add tests for row order tag templates

app/helpers/barcode_labels_helper.rb, app/helpers/page_helper.rb, app/helpers/plate_helper.rb, app/models/limber/plate.rb, app/views/labware/_barcode_printing_form.html.erb, app/views/labware/plates/_tube_printing.html.erb, spec/factories/barcode_printer_factories.rb, spec/factories/plate_factories.rb, spec/features/viewing_a_plate_spec.rb, spec/models/presenters/standard_presenter_spec.rb
=> Fix barcode printing

app/helpers/plate_helper.rb, app/models/labels/tube_label.rb, config/label_templates.yml, lib/tasks/add_limber_tube_label_template.rake, lib/tasks/test_config.rake, spec/controllers/print_jobs_controller_spec.rb
label_templates.yml file should be updated in deployment project
=> Seq375 tube label

Gemfile, Gemfile.lock, app/assets/stylesheets/limber/screen.scss, app/controllers/labware_controller.rb, app/models/limber/plate.rb, app/models/limber/well.rb, app/models/presenters/plate_presenter.rb, app/models/presenters/presenter.rb, app/models/presenters/unknown_labware_type.rb, app/models/validators/suboptimal_validator.rb, app/views/application/_warnings.html.erb, app/views/labware/_aliquot.html.erb, app/views/plates/show.html.erb, spec/factories/plate_factories.rb, spec/factories/well_factories.rb, spec/factory_outputs/plate_factory_spec.rb, spec/features/viewing_a_plate_spec.rb, spec/models/presenters/plate_presenter_spec.rb, spec/models/presenters/shared_labware_presenter_examples.rb, spec/models/presenters/tube_presenter_spec.rb
Includes the PCR free warnings https://github.com/sanger/limber/pull/17 as depends on the warning bar.
=> Add quality warning to wells

config/purposes/genotype_by_sequencing.yml
- Update GBS templates
- Fix tube display
=> Release-1.5.1

.travis.yml, Gemfile.lock, yarn.lock
- Updated some gems and node_modules
- Working with node 10.2.0
=> Security fix

config/purposes/low_input.yml, config/robots.rb
Deploy:
`bundle exec rake config:generate`
=> Seq-685  Added RNAR and RNARG purposes and robot bed verifications

app/views/application/_header.html.erb
- Stop hardcoding the environment
- Hide the badge in production
=> Environment badge shows correct environment

Gemfile, Gemfile.lock
Having issues with older deployment servers and github
=> Switch to rubygems deployment of client gem

app/models/sibling.rb
symbols respond to :[] Switch to fetch to fix
behaviour
=> Missing tubes handled correctly

config/purposes/000_wgs_isc_top.yml
=> Added TSISC_UDI96 tag layout template

lib/deployed_version.rb
- Fix filtering of requests by state
=> Release-2.3.3

yarn.lock
Had issues running yarn install locally, updating these dependencies fixes it.
=> Resolve yarn issues

config/robots.rb
Bed verification robot configs for the Chromium Automated pipeline.
Frag 2XP and LigXP plate steps.
=> GPL090 - Robot bed verifications for chromium frag 2xp and ligxp plates

app/controllers/exports_controller.rb, app/views/exports/hamilton_gex_dil_to_gex_frag_2xp.csv.erb, app/views/exports/hamilton_gex_frag_2xp_to_gex_ligxp.csv.erb, config/purposes/bespoke_chromium_automated.yml, spec/controllers/exports_controller_spec.rb, spec/views/exports/hamilton_gex_dil_to_gex_frag_2xp.csv.erb_spec.rb, spec/views/exports/hamilton_gex_frag_2xp_to_gex_ligxp.csv.erb_spec.rb
CSV files for two more steps in the chromium automated pipeline.
For Frag 2XP and LigXP plate creation steps.
=> GPL089 CSV files for chromium automated Frag 2xp and ligxp plates

.travis.yml, app/models/robots/bed/bed_error.rb, app/models/state_changers.rb, app/sequencescape/sequencescape/api/v2.rb, app/sequencescape/sequencescape/api/v2/plate.rb, app/sequencescape/sequencescape/api/v2/well.rb, config/purposes/bespoke_chromium_automated.yml, spec/factories/plate_factories.rb, spec/factories/purpose_config_factories.rb, spec/factories/request_factories.rb, spec/models/state_changers_spec.rb
Added automatic work completion state changer.
Used in Chromium 10X automated pipeline to automatically close off Aggregation requests once the LBC Cherrypick plate has been made.
=> GPL093 - Automatic work completion for aggregation in chromium 10X

app/controllers/exports_controller.rb
Chromium 10X VDJ pipelines change to workflow name in csv files produced in TCR and BCR pipelines for post ligation single spri step.
=> GPL-189 Change to csv workflow header for TCR and BCR options

config/purposes/duplex_seq.yml
Initial version of purposes configuration.
=> Gpl292 duplex seq purposes config

Gemfile.lock, app/models/labels/base.rb, app/models/labels/plate_label_lds_al_lib.rb, app/models/labels/plate_label_xp_base.rb, app/models/labels/plate_split.rb, app/views/labware/_barcode_printing_form.html.erb, config/label_templates.yml, spec/models/presenters/plate_presenter_spec.rb
- 3 QC labels plus 3 intermediate labels
- Print label configuration changes to qc_attributes to make array of hashes
- Addition of new section for intermediate_attributes for the new intermediate labels
=> Gpl294 Adds label printing for duplex_seq LDS Al Lib plate

config/pipelines/high_throughput_duplex_seq.yml
Initial version of pipeline configuration.
=> Gpl291 duplex seq pipeline config

app/models/labware_creators/pcr_cycles_binned_plate.rb, spec/models/labware_creators/pcr_cycles_binned_plate/csv_file_spec.rb
Still got to add the 'diluent_volume' into the fields to update, but that will be a tiny change.
=> Gpl295 duplex seq labware creator

.travis.yml
Reverts sanger/limber#399
Didn't need to do this!
=> Revert "Removed branch from deploy for travis."

config/label_templates.yml, config/purposes/heron.yml
=> Fix for bug where PCR 1 and 2 labels not printed

config/pipelines/high_throughput_heron.yml
Merge Andrew's PR first, then the diff will make more sense
=> Gpl 369 rename heron library type

config/pipelines/high_throughput_heron_384.yml, config/purposes/heron_384.yml, config/robots.rb
Name changes to the bed verification for the AL Lib plate and to the name for the XP pool tube, requested after UAT
=> GPL393 scaling for 384 well plates - post UAT fixes

app/assets/stylesheets/limber/plate.scss, app/controllers/plates_controller.rb, app/javascript/shared/transfersLayouts.js, app/models/labware_creators/quadrant_stamp_base.rb, app/sequencescape/sequencescape/api/v2/well.rb, app/views/aliquots/_standard_aliquot.html.erb, spec/factories/sample_factories.rb, spec/features/creating_a_tag_plate_spec.rb, spec/sequencescape/api/v2/well_spec.rb
=> Gpl 431 see location of floating controls

config/pipelines/high_throughput_heron.yml
Adds the new Heron library types to the 96 pipelines
=> Add New library types to Heron pipeline

app/models/labels/plate_split.rb, config/pipelines/high_throughput_heron.yml
Adds new library types to limber pipeline
=> Adds new library types to limber pipeline

.rubocop.yml, Gemfile, Gemfile.lock, app/helpers/page_helper.rb, app/helpers/search_helper.rb, app/models/robots/pooling_robot.rb
Updates Rubocop and adds rubocop-performance
Does auto-corrects or adds rubocop:disable as required
=> Rubocop updates

app/views/plate_creation/merged_plate.html.erb, config/locales/en.yml, config/robots.rb
=> Heron tailed workflow fix

Gemfile, Gemfile.lock, app/assets/javascripts/merged_plate.js, app/assets/javascripts/tag_by_tag_plate.js, app/models/labware_creators/tagged_plate.rb, app/views/plate_creation/merged_plate.html.erb, app/views/plate_creation/tagged_plate.html.erb, spec/models/labware_creators/tagged_plate_spec.rb, spec/spec_helper.rb, spec/support/shared_tagging_examples.rb
=> Disable clash detection when not required

config/pipelines/bespoke_pcr.yml
=> Added hic library types to bespoke pcr pipeline.

config/pipelines/high_throughput_heron_384_tailed.yml, config/pipelines/high_throughput_heron_96_tailed.yml
RT-705000
Ensure library types appear in both forks.
=> Hotfix: PCR 2 pathways for new LT

config/purposes/heron_lthr_384.yml
=> Update template names

config/pipelines/high_throughput_heron_96_tailed.yml, config/purposes/heron_lthr_96.yml, config/robots.rb
Addtional stamp step at top end of processed missed in first
requirement:
Yes we will need to do the additional stamp of 10 ul. The instrument
used will be the Bravo (same instrument used for the 96 to 384
consolidation). The source bed will be Bed 1 and the destination bed 5.
=> Add Additional stamp step at top end of pipeline

config/pipelines/high_throughput_heron_96_tailed.yml
=> Fix PCR2 fork

app/assets/javascripts/choose_workflow.js, app/assets/javascripts/lib/disable_enter_key_submit.js, app/assets/javascripts/merged_plate.js, app/controllers/concerns/sequencescape_submission_behaviour.rb, app/models/sequencescape_submission.rb, app/views/plates/_choose_workflow.html.erb, config/purposes/heron_lthr_entry.yml, spec/models/sequencescape_submission_spec.rb
=> GPL-851 Make 'choose workflow' page respond better to scanners

app/controllers/concerns/sequencescape_submission_behaviour.rb, app/models/presenters/submission_plate_presenter.rb, app/models/sequencescape_submission.rb, app/views/plates/_choose_workflow.html.erb
add validation to prevent following:
- same barcode being scanned more than once accidentally
- scanning the barcode of the page we're on due to misunderstanding
=> GPL-851 additions

app/sequencescape/sequencescape/api/v2/tube.rb, spec/sequencescape/api/v2/tube_spec.rb
=> Added sort for tube stock plate along with dodgy test.

app/javascript/plain-javascript/quadrant-well-failing.js
=> Only bind quadrant helper if it exists

README.md, config/pipelines/bespoke_pcr.yml
Closes GPL921
* Add new library type Haplotagging for Limber Bespoke - PCR
=> Add new library type Haplotagging

config/robots.rb
Also see associated Integration Suite PR here: https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/26
=> DPL-035 and 036 surge testing bed verifications

app/controllers/search_controller.rb
=> Fix for search error message

app/sequencescape/sequencescape/api/v2/labware.rb
=> DPL-017 Fix for human_barcode lookup on labware

.tours/lcmb.tour
=> Add LCMB code tour

app/javascript/multi-stamp-tubes/components/MultiStampTubes.vue, app/javascript/shared/components/LabwareScan.vue
Adds scrolling to the TubeScans panel on the right of the screen.
=> Dpl064 scrolling tube scans panel

app/models/presenters/qc_threshold_presenter.rb, app/views/plates/_threshold.html.erb, config/purposes/cardinal.yml, docs/purposes_yaml_files.md, spec/models/presenters/qc_threshold_presenter_spec.rb
- Detach fields from form so validation is non-blocking
- Allow customized 'step' values
- Use same step for range and inputs
- Ensure max and min conform to step
=> Fix form validation issues

package.json, yarn.lock
=> Move @babel/preset-env to prod env

app/models/labware_creators/multi_stamp_tubes.rb, app/sequencescape/sequencescape/api/v2/study.rb, spec/models/labware_creators/multi_stamp_tubes_spec.rb
Closes #887 
Allows tubes with different studies to be arrayed together and submitted.
=> Dpl154 cardinal submissions allow source tubes with different studies

app/models/concerns/labware_creators/require_wells_with_sample_manifest.rb, app/models/labware_creators/cardinal_pools_plate.rb, spec/models/labware_creators/cardinal_pools_plate_spec.rb
=> Added concern to validate sample manfiest presence

app/models/presenters/tube_presenter.rb, spec/models/presenters/tube_presenter_spec.rb
Closes #903 
Fixes an issue discovered in UAT
=> Ensure missing transfer parameters are handled

app/views/labware/_tube.html.erb, app/views/plate_creation/custom_tagged_plate.html.erb, app/views/plate_creation/multi_stamp.html.erb, app/views/plate_creation/multi_stamp_tubes.html.erb, app/views/plates/_common_tabbed_pages.html.erb, app/views/tube_rack_creation/tubes_to_rack.html.erb, app/views/tube_racks/summaries/_default.html.erb, app/views/tubes/sidebars/_default.html.erb, app/views/tubes/validate_paired_tubes/index.html.erb, config/environments/development.rb, config/environments/test.rb
Closes #933 
* JavaScript needs a different localhost URL for the SequenceScape v2 API than the rest of the Rails app.  While requests from the Rails app come from the Docker container Limber is running in, JavaScript requests come from the browser and that doesn't know what the special domain means for Docker containers calling back to the host machine.
=> Docker tweak

app/javascript/validate-paired-tubes/components/TransferVolumes.spec.js, app/javascript/validate-paired-tubes/components/TransferVolumes.vue
=> Display 2 DP instead of 1 for transfer volumes

config/pipelines/high_throughput_cardinal.wip.yml, config/purposes/cardinal.wip.yml
=> DPL-195 Modify Cardinal pipeline to use existing Chromium library type

app/models/labels/plate_label_ltn_al_lib.rb, app/views/exports/targeted_nanoseq_al_lib_concentrations_for_customer.csv.erb, app/views/exports/targeted_nanoseq_pcr_xp_concentrations_for_custom_pooling.csv.erb, config/exports/exports.yml, config/label_templates.yml, config/pipelines/high_throughput_duplex_seq.yml, config/pipelines/high_throughput_isc.yml, config/pipelines/high_throughput_targeted_nanoseq.yml, config/purposes/targeted_nanoseq.yml, config/robots.rb, spec/controllers/exports_controller_spec.rb, spec/fixtures/config/exports/exports.yml, spec/lib/config_loader/exports_loader_spec.rb, spec/views/exports/targeted_nanoseq_al_lib_concentrations_for_customer.csv.erb_spec.rb, spec/views/exports/targeted_nanoseq_pcr_xp_concentrations_for_custom_pooling.csv.erb_spec.rb
Closes #928 
Also see Sequencescape and Integration Suite PRs of same name.
=> Dpl183 targeted nanoseq

app/views/tube_creation/pooled_tubes_by_sample.html.erb
- in cardinal cell banking pipeline
- it was inaccurate
=> Update tube rack scan upload page guidance text

app/views/exports/hamilton_pooling_plate_pbmc.csv.erb, spec/views/exports/hamilton_pooling_plate_pbmc.csv.erb_spec.rb
=> DPL-256 & DPL-207 cardinal hamilton pooling file tweaks

app/controllers/pipeline_work_in_progress_controller.rb
update Heron 'work in progress' view to refer to new pipeline versions
=> Fix 'work in progress' view

config/robots.rb
Fix after Scott G UAT feedback
=> Combined LCM bed verification update

app/models/robots/bed/base.rb, app/models/robots/robot.rb, config/robots.rb, lib/robot_configuration.rb, spec/models/robots/robot_spec.rb
=> DPL265 bed verification for phix

app/assets/javascripts/bed_verification.js, app/models/robots/robot.rb, spec/models/robots/robot_spec.rb
=> Dpl265 bed verification phix

config/robots.rb
Disabled config for bed 28 PhiX tube until Lab ready at later date.
=> DPL265 - Removed references to Bed 28 for the PhiX tube

app/assets/javascripts/bed_verification.js
Fix for bug identified after Training session by Iraad
=> DPL265 - Fix for not clearing the bad bed flags

app/controllers/creation_controller.rb
=> GPL-403 Fix to allow both arrays and single strings for error message parameter

app/javascript/shared/components/plateScanValidators.js, app/javascript/shared/components/plateScanValidators.spec.js
=> Sort new list

lib/purpose_config.rb
=> Added ng/ul download for qc as a default.

app/models/concerns/presenters/extended_csv.rb, app/models/limber/plate.rb, app/models/presenters/plate_presenter.rb
=> RT757322 Use human barcode and machine barcode instead of ean13 and prefix+number

app/javascript/test_support/factories/json_factory.js
Fix for depfu fail on update of webpack-dev-server
=> Fix for breaking change to how uuid v4 should be imported

package.json, yarn.lock
Attempt to fix depfu dependency update for babel
=> Updated babel dependencies

.github/workflows/append_release.yml, .github/workflows/automated_release.yml
=> Add Node setup steps to build pipelines

config/mbrave.yml
=> Add training

config/robots.rb
=> Fix for Bioscan bed verifications to require users to scan a robot barcode

app/models/labware_creators/stamped_plate_adding_randomised_controls.rb, config/purposes/bioscan.yml, spec/factories/purpose_config_factories.rb, spec/models/labware_creators/stamped_plate_adding_randomised_controls_spec.rb
Also added restriction to not use well H12
=> Bioscan dpl568 labware creator tests

config/robots.rb
Closes #1258 
* update GBS bed verification in line with DPL-703 story
=> DPL-703 - GbS bed verification changes

app/assets/stylesheets/limber/screen.scss
=> Bioscan UAT fixes 23rd June

config/mbrave.yml, config/purposes/bioscan.yml
=> Added version 1

config/robots.rb
This reverts commit 976b09873e7f4a771a6eb9c0c672224701073ab1.
Reverting while Bioscan gets released.
=> Revert "update GBS bed verification in line with DPL-703 story"

app/helpers/exports_helper.rb, app/views/exports/bioscan_mbrave.tsv.erb
=> Fix mod 4 tags

spec/factories/well_factories.rb, spec/views/exports/bioscan_mbrave.tsv.erb_spec.rb
=> Test for bioscan generation change

config/robots.rb, lefthook.yml
Closes #1327 
Adds 4 bed verification configurations for LCMB pipeline
=> Dpl 824 add lcmb bed verifications

config/robots.rb
update GBS bed verification in line with DPL-703 story (again, after reverting to make room for another release)
=>  DPL-703 GBS bed verification (putting back in after reverting)

.github/workflows/ruby_test.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
Attempt to fix webdrivers gem issue where cannot get version 115 of chrome driver
=> Bugfix webdrivers

app/javascript/asset-comments/index.js, app/javascript/custom-tagged-plate/components/CustomTaggedPlate.spec.js, app/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue, app/javascript/multi-stamp-tubes/components/MultiStampTubes.vue, app/javascript/multi-stamp/components/MultiStamp.vue, app/javascript/shared/devourApi.js, app/javascript/test_support/mock_api.js, app/javascript/tubes-to-rack/components/TubesToRack.vue, app/javascript/validate-paired-tubes/components/ValidatePairedTubes.vue, app/sequencescape/sequencescape/api/v2/base.rb, app/views/labware/_tube.html.erb, app/views/plate_creation/custom_tagged_plate.html.erb, app/views/plate_creation/multi_stamp.html.erb, app/views/plate_creation/multi_stamp_library_splitter.html.erb, app/views/plate_creation/multi_stamp_tubes.html.erb, app/views/plates/_common_tabbed_pages.html.erb, app/views/plates/sidebars/_default.html.erb, app/views/tube_rack_creation/tubes_to_rack.html.erb, app/views/tube_racks/summaries/_default.html.erb, app/views/tubes/sidebars/_default.html.erb, app/views/tubes/validate_paired_tubes/index.html.erb, config/environments/development.rb, config/environments/test.rb
Closes #1322 
- Add the API key for Sequencescape to V2 endpoint requests.
=> DPL-670-3 Use Sequencescape API key

config/purposes/lcmb.yml, config/robots.rb
Adhoc fix for RT about LCMB tag templates here https://rt.sanger.ac.uk/Ticket/Display.html?id=785454
And for email from Liz E re: LCMB bed verification bed number incorrect
=> LCMB fix for bed number and tag templates

config/robots.rb
Closes #1334 
Added bed verification
=> DPL-830 Added bed verification for LRC PBMC Bank step

config/pipelines/high_throughput_scrna_core_cell_extraction.wip.yml, config/purposes/scrna_core_cell_extraction.yml, docs/creators.md, docs/presenters.md, docs/state_changers.md
Closes #1347 
Added LRC Blood Aliquot tube step
=> Added LRC Blood Aliquot tube step

app/models/labware_creators/plate_split_to_tube_racks.rb, app/models/labware_creators/well_filter.rb, app/models/labware_creators/well_filter_allowing_partials.rb, app/views/exports/hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare.csv.erb, config/exports/exports.yml, spec/factories/tube_factories.rb, spec/models/labware_creators/plate_split_to_tube_racks_spec.rb, spec/views/exports/hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare.csv.erb_spec.rb
Closes #1362 
Fixes the driver file for the transfer from PBMC Bank to Seq and Spare FluidX Tubes
=> DPL-878 Added csv driver download for PBMC Bank to FluidX Seq and Spare tubes

config/mbrave.yml, config/purposes/bioscan.yml
=> New tag layout template bioscan v3

config/purposes/combined_lcm_dna_and_rna_seq.yml, config/purposes/duplex_seq.yml, config/purposes/heron.yml, config/purposes/heron_lthr_96.yml, config/purposes/lcmb.yml, config/purposes/scrna.yml, config/purposes/targeted_nanoseq.yml, config/purposes/wgs_isc_top.yml, spec/fixtures/config/purposes/test_set_a.yml
Closes #1405 
Added new tag layout template to Limber pipeline configs
=> DPL-929 - added new tag layout template

config/pipelines/bespoke_chromium_3pv3.yml, config/pipelines/bespoke_chromium_5p.yml, config/pipelines/bespoke_chromium_bcr.yml, config/pipelines/bespoke_chromium_tcr.yml
Closes #
- Added HT library types for limber_chromium_bespoke pipelines config for 10X
=> DPL-872 Added HT library types for limber_chromium_bespoke pipelines config

app/models/labware_creators/plate_split_to_tube_racks.rb, app/models/labware_creators/plate_split_to_tube_racks/csv_file.rb, spec/models/labware_creators/plate_split_to_tube_racks/csv_file_spec.rb
=> scRNA file validation fix - added check for valid files

config/robots.rb
=> DPL-937 - RVI Lib PrePool robot bed verifications

config/exports/exports.yml
Adds barcode to filenames for the two hamilton driver files
=> scRNA fix - to add barcodes to export filenames

app/models/presenters/rvi_cdna_xp_presenter.rb, config/locales/en.yml, config/pipelines/high_throughput_rvi_bcl.wip.yml, config/purposes/rvi.wip.yml, config/robots.rb, docs/presenters.md, spec/models/presenters/rvi_cnda_xp_presenter_spec.rb
- Adds RVI prefix to bait capture library pipeline
- Updates robot verifications for rvi bcl pipeline
- Adds custom presenter to RVI cDNA plate to allow custom 'Manual transfer' state change.
=> DPL-937 - Updates to RVI BCL pipeline

config/pipelines/high_throughput_rvi_bcl.wip.yml
- renames pipeline_group to add 'RVI' for rvi bcl pipeline
=> DPL-937 - RVI BCL pipeline_group rename

config/robots.rb
- Updates bed verification for RVI cDNA XP Frag mix to bed 8 from bed 5
=> DPL-937 -  Changes cDNA frag mix bed verification to bed 8

app/models/presenters/failable_stock_plate_presenter.rb, config/purposes/bioscan.yml, config/robots.rb, spec/models/presenters/failable_stock_plate_presenter_spec.rb
=> Revert "Revert "DPL-960 - Bioscan input plate state changes""

.github/workflows/append_release.yml, .github/workflows/automated_release.yml, .github/workflows/check_release_version.yml, .github/workflows/js_test.yml, .github/workflows/lint.yml, .github/workflows/ruby_test.yml
- Updates various ci actions to use latest versions
=> Housekeeping: Updates various ci actions to use latest versions

app/models/concerns/presenters/statemachine/permissive.rb, app/models/concerns/presenters/statemachine/single_child_permissive.rb, app/models/concerns/presenters/statemachine/standard.rb, app/models/concerns/presenters/statemachine/submission.rb, config/robots.rb
Adds state processed-4
Adds bed verification for RVI RT step, processed-3 to processed-4
Has related SS and integration suite changes
=> DPL-1032 RVI - added state processed 4 and bed verification

config/robots.rb
- Changes bed from 8 to 6 for Bravo RVI RT First Strand Mix
=> DPL-937 - Bed verification update for RVI RT First Strand Mix bed

docs/pipelines_yaml_files.md, docs/purposes_yaml_files.md
- Add documentation about pipeline_group
=> Add documentation about pipeline_group

app/views/exports/pbmc_bank_tubes_content_report.csv.erb, spec/views/exports/pbmc_bank_tubes_content_report.csv.erb_spec.rb
Closes #
- Change volume - requested by R&D after training
- Apparently 135ul was never correct (there might have been confusion over the fact that there will be 135ul in the LRC PBMC Bank well, however only 125ul of that will be transferred to the child tubes).
Ideally get Abby to verify this change in UAT, although no special need for it to delay release as it's v low risk.
=> Change volume - requested by R&D after training

app/sequencescape/sequencescape/api/v2/plate_purpose.rb, lib/purpose_config.rb
Closes #
- Register plate purposes via SS API v2
=> DPL-969 [Limber] Support for Chromium chip labware

config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml
Closes #
- Updated pipeline filters for scRNA Donor Pooling and cDNA Prep
=> DPL-913 [Limber] Submit banked PBMC tubes for cDNA prep

config/purposes/scrna_core_cdna_prep.wip.yml
Closes #1389 
- Add cell counting functionality onto the LRC PBMC Defrost PBS plate
=> DPL-915 Count thawed cells

app/controllers/exports_controller.rb, app/helpers/exports_helper.rb, app/views/exports/hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools.csv.erb, config/exports/exports.yml, config/purposes/scrna_core_cdna_prep.wip.yml, spec/views/exports/hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools.csv.erb_spec.rb
=> DPL-1024 PBMC donor pooling - driver file

app/views/plate_creation/donor_pooling_plate.html.erb
Closes #
- Show the number of source plates to scan in 
- Make input fields optional
- Fix missing end to form_for block
=> DPL-916-2 PBMC donor pooling fixes

app/javascript/custom-tagged-plate/components/CustomTaggedPlate.spec.js, app/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue, app/javascript/shared/components/Well.vue
Closes #1631 
Fix for bug in tagging screen where wells are invisible
=> Y24-029 Bug fix for invisible wells issue in tagging screen

config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml, config/purposes/scrna_core_cdna_prep.wip.yml
Closes #
- Update Limber configuration to merge donor pooling and cDNA Prep request types into a single request type.
=> DPL-916-6 [limber] PBMC donor pooling submission with unified request

app/models/labware_creators/pcr_cycles_binned_plate_for_t_nano_seq.rb, spec/fixtures/files/targeted_nano_seq/targeted_nano_seq_dil_file_loop.csv, spec/models/labware_creators/pcr_cycles_binned_plate_for_t_nano_seq_spec.rb, spec/support/api_url_helper.rb
Closes #1628 
Adds check for whether metadata with same key already exists on the request, if it does update it (if value different than current).
=> Y24-028 Targeted Nanoseq - fix to allow metadata update

config/purposes/scrna_core_cdna_prep.wip.yml
Closes #1397 
- Changes to binning config based on Abby feedback during UAT of DPL-924
- The config may change again, but this is closer to correct
- Associated change in Int Suite - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/130
=> DPL-924 Changes to binning config based on R&D feedback

config/robots.rb
Closes #1678 
Added alternate Bravo robot bed verification.
=> Y24-068 RVI - added alternate bravo bed verification for deep well stamping

config/robots.rb
Closes #1504 
Adds 2 bed verifications for the LRC PBMC Defrost PBS to LRC PBMC Pools step
=> DPL-1025 scRNA - added bed verifications for scrna pbmc defrost pbs to pbmc pools step

config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml
Closes #1392 
- Added version suffixes to the pipeline library types
=> DPL-919 - Added version suffixes to library types

app/models/presenters/tube_presenter.rb
=> BUG fix - changed syntax to remove fetch

app/models/utility/cell_count_spot_checking.rb, config/exports/exports.yml, config/purposes/scrna_core_cdna_prep.wip.yml, config/purposes/scrna_core_cell_extraction.yml, spec/models/utility/cell_count_spot_checking_spec.rb
Closes #
- Update algorithm to pick first wells for each Vac tube
- Update Count CSV file names and download button labels
=> Y24-037 UAT Update - Cell Count Spot Checking

spec/models/utility/cell_count_spot_checking_spec.rb, spec/views/exports/hamilton_lrc_pbmc_bank_to_cellaca_common.csv.erb_spec.rb
Closes #
- Renaming templates were pushed directly to develop by mistake.
- Update tests with the new template names.
=> Y24-037 Update tests with new template names

app/models/labels/plate_label_96_lysate.rb, config/label_templates.yml, config/pipelines/high_throughput_anospp.wip.yml, config/pipelines/high_throughput_genotype_by_sequencing.yml, config/purposes/anospp.yml, config/purposes/bioscan.yml, config/robots.rb, spec/models/labels/plate_label_96_lysate_spec.rb
=> Y24-136 anospp pipeline config

README.md
Closes #1709 
- Reordered the steps for setting up Limber so that one application is setup before another, clearly outlining how many terminals are needed.
- Added some detail on what some of the steps and rake tasks do.
=> Y24-109 - Rework Limber documentation for clarity on how SequenceScape & Limber interact and are setup

app/models/utility/cell_count_spot_checking.rb, spec/models/utility/cell_count_spot_checking_spec.rb
Closes #
- Filter out failed wells, which shifts the wells to the failed well positions in the downloads. 
=> Y24 041 uat update 4 cell count spot checking

config/robots.rb
Closes #
- copy paste error - new (ANOSPP) version of the (Bioscan) robot config was overwriting the old version, because the keys were the same
=> Bioscan fix

config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml, config/purposes/scrna_core_cdna_prep.wip.yml, config/purposes/scrna_core_cell_extraction.yml
Closes #https://github.com/sanger/sequencescape/issues/4159
Added config for LRC Bank Input tube
=> Y24-169 Added config for LRC Bank Input tube

config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml, config/purposes/scrna_core_cdna_prep.wip.yml
Closes #1768
- updates request type for scrna core cdna prep
Requires: https://github.com/sanger/sequencescape/pull/4222
Integration suite branch: y24-178-modify-cdna-prep-submission
=> Y24-178 - Modify scRNA cDNA prep request types

config/purposes/scrna_core_cdna_prep.wip.yml
Closes #
- Update request type name after it was changed in Y24-178
=> Y24-178 fix

app/javascript/shared/wellHelpers.spec.js
Closes #
- Split out scenarios to improve tests
=> Split out scenarios to improve tests

config/purposes/scrna_core_cell_extraction.yml
Closes #
- Change presenter to a stock tube presenter for LRC Bank Input
=> DPL-989 UAT Update LRC Bank Input Presenter

app/models/presenters/minimal_pcr_plate_presenter.rb, app/models/presenters/pcr_with_primer_panel_plate_presenter.rb, app/models/presenters/plate_presenter.rb, app/views/labware/plates/_pcr_with_primer_panel_summary.html.erb, config/purposes/genotype_by_sequencing.yml
Closes #1781 
- adds a new presenter for PCR that allows well failing
=> Y24-197 GBS - allow well failing on PCR1 plate

config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml, config/purposes/scrna_core_cdna_prep.wip.yml
Closes #1813 
- Changed request type key and name for scRNA Core cDNA Prep Input
- Changed work completion request type to align with new request type key
=> Y24-214 - Modify scRNA Core cDNA Input request type

config/robots.rb
Closes #
- Add missed bed verification for scRNA Core pipeline, aggregation part (came up in UAT of DPL-971)
- copied from equivalent step in existing Chromium Bespoke pipeline
See related Integration Suite pull request - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/152 
=> DPL-971 add missed bed verification

app/sequencescape/sequencescape/api/v2/tube_rack_purpose.rb, config/purposes/tube_racks.yml, lib/purpose_config.rb, spec/fixtures/config/purposes/test_set_a.yml, spec/lib/config_loader/purposes_loader_spec.rb
Closes #1695 
- Adds tube racks for 'LRC Bank Seq' and 'LRC Bank Spare'
Linked to https://github.com/sanger/sequencescape/pull/4314/
=> Y24-098 - Tube rack banking purposes

app/models/labware_creators/pooled_tubes_by_submission_with_phi_x.rb, spec/models/labware_creators/plate_split_to_tube_racks_spec.rb
- Fix the attribute name for Phi X tube creations.
- Remove some redundant test code.
=> Y24-190-3 Fix SpecificTubeCreation

app/views/exports/hamilton_lrc_pbmc_pools_to_cellaca_count.csv.erb, config/exports/exports.yml, config/purposes/scrna_core_cdna_prep.wip.yml, spec/views/exports/hamilton_lrc_pbmc_pools_to_cellaca_count.csv.erb_spec.rb
Closes #1915 
- Adding the driver file.
Integration suite PR (well, "Merge Request" to be precise): https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/168
=> Add Hamilton LRC PBMC Pools to Cellaca Count CSV export

config/robots.rb
Activates the GBS plus ANOSPP version of the GBS bed verification
=> ANOSPP - activate GBS plus ANOSPP version of bed verification

.github/workflows/update_rubocop.yml
Closes https://github.com/sanger/General-Backlog-Items/issues/433
- Bumped `checkout` dependency to v4.
=> Y24-244 - Update checkout dependency to v4

app/models/concerns/labware_creators/donor_pooling_calculator.rb, app/models/labware_creators/donor_pooling_plate.rb, config/initializers/scrna_config.rb, spec/models/concerns/labware_creators/donor_pooling_calculator_spec.rb, spec/models/labware_creators/donor_pooling_plate_spec.rb
Closes #1992 
Adds the calculations to check for full allowance, adjusting number of cells per chip well if needed and storing that value on the destination pool wells for use in creating the driver file for loading the chip plate later.
=> Y24-384 scRNA - adjust pooling for full allowance

config/robots.rb
Closes #
- scRNA bed verification for LRC GEM-X 5p cDNA PCR to LRC GEM-X 5p cDNA PCR XP
Integration Suite changes: [DPL-922 PR [Integration] Transfer into cDNA PCR XP plate](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/200)
=> DPL-922 PR [Limber] Transfer into cDNA PCR XP plate

config/pipelines/high_throughput_lcm_triomics.wip.yml, config/purposes/lcm_triomics.wip.yml
Closes #
- Use the pre-existing library type emSEQ for the EMSeq branch
- Use the library type LCMB for the WGS branch
=> Y24-194 PR [Limber] UAT Updates 3 LCM WGS EMSeq pipeline configuration and integration test

app/frontend/stylesheets/limber/screen.scss, app/helpers/page_helper.rb, app/models/presenters/tube_rack_presenter.rb, app/sequencescape/sequencescape/api/v2/tube.rb, app/sequencescape/sequencescape/api/v2/tube_rack.rb, spec/factories/tube_rack_factories.rb, spec/sequencescape/api/v2/tube_rack_spec.rb
Closes #2090 
Move state method to v2 TubeRack model
=> moved state to v2 tube rack and reinstated presenter state badge

lefthook.yml
added format compact to lefthook commands to fix eslint error with formatter stylish
=> BUG: fix - lefthook

app/models/presenters/tube_rack_presenter.rb, app/models/tube_rack_walking.rb, app/sequencescape/sequencescape/api/v2/tube_rack.rb, app/views/tube_racks/sidebars/_default.html.erb, config/robots.rb
Closes #2108 
Adds buttons for bed verifications, manual transfer and other actions to Presenter view
Functionality behind those still WIP
=> Y24-498 scRNA Tube Racks - add buttons for bed verification and manual transfers

app/models/robots/robot.rb, app/views/robots/show.html.erb, config/robots.rb, spec/models/robots/robot_spec.rb
Closes #2075
- Adds start_button_text config option for robots.
=> Y24-463 - Custom start button text for robots

config/robots.rb
- Adds missing 'Bravo' text from LCM robots with custom start button text. 
Updated in int suite but forgot to push here 🤦‍♂️
=> Y24-463 - Custom robot text 

app/frontend/javascript/file-list/components/FileList.spec.js, app/frontend/javascript/file-list/components/FileList.vue, app/frontend/javascript/vue_app.js
Closes https://github.com/sanger/limber/issues/2131
This includes the fix for bug - Uploaded files not displayed in File tab
=> fix(file-list): Fix for uploaded files not displayed in file tab

app/models/presenters/tube_rack_presenter.rb, app/views/tube_racks/_rack_printing.html.erb, app/views/tube_racks/sidebars/_default.html.erb, spec/models/presenters/tube_rack_presenter_spec.rb
=> Y24 103 tuberack presenter - removed label printing options

app/models/validators/in_progress_validator.rb, app/sequencescape/sequencescape/api/v2/shared/has_requests.rb, spec/features/viewing_a_minimal_plate_spec.rb, spec/features/viewing_a_plate_spec.rb
Closes https://github.com/sanger/limber/issues/2110
- Refine validation to check for completed non-create asset requests
=> Y24 502 fix incorrect warning active submission requests

config/sprint/label_templates/plate_384.yml.erb, config/sprint/label_templates/plate_96.yml.erb
Closes #
- Tweak the plate_96 and plate_384 templates by comparing with the Deployment project.
=> Y25-067 - [PR][Limber] Synchronise Limber and Deployment sprint templates

app/frontend/javascript/custom-tagged-plate/components/TagOffset.vue
Closes #
add text under the offset field
- 
=> add offset message

app/models/state_changers.rb, config/purposes/scrna_core_cell_extraction.yml, spec/models/state_changers_spec.rb
=> Y24 459 fix

config/exports/exports.yml, config/pipelines/high_throughput_scrna_core_cdna_prep.yml, config/purposes/scrna_core_cdna_prep.yml, config/robots.rb
Closes #2206
- Added limber config for the CITE-Seq pipeline variation.
=> Y25-100 - CITE-Seq Pipeline Variation

app/views/exports/pbmc_bank_tubes_content_report.csv.erb, spec/views/exports/pbmc_bank_tubes_content_report.csv.erb_spec.rb
Closes #2232
- Updates PBMC Bank tubes content report to use tube racks.
=> Y25-155 - PBMC Bank tubes content report CSV to use Tube Racks

spec/models/robots/robot_spec.rb
Created during testing of support issue around bed verifications by Sara W.
Cannot replicate her issue, but may as well merge in the extra tests.
=> Bed verification - added additional tests around layouts with pairs of beds

config/pipelines/kinnex.wip.yml
=> Removing library pass (unnecessary)

.github/workflows/update_rubocop.yml
Closes #2216 
- This job now uses the reusable workflow which can be found [here](https://github.com/sanger/.github/blob/master/.github/workflows/update-rubocop.yml).
=> Y25-107-5 - Migrate & Improve update_rubocop workflow

.github/workflows/compile_test.yml
Closes #2216 
- Migrated setup steps to use the composite actions
- Migrated the release steps to use the composite actions
- Minor improvements to syntax and structure
=> Y25-107-6 - Migrate & Improve compile_test workflow
