sanger/limber

- Gemfile
- Gemfile.lock
- app/models/labware_creators/pooled_tubes_by_submission.rb
- spec/factories/tube_factories.rb
- spec/models/labware_creators/pooled_tubes_by_submission_spec.rb
This backport the tube naming changes from the low input work.
> Fix tube naming

- app/models/labware_creators/pooled_tubes_by_submission.rb
- lib/well_helpers.rb
- spec/factories/plate_factories.rb
- spec/factory_outputs/plate_factory_spec.rb
- spec/models/labware_creators/pooled_tubes_by_submission_spec.rb
While the wells were sorted, they were sorted in row order,
not column order. This updates the tests to match Sequencescape
and ensures that the tested ranges behave differently.
> Order wells into column order before naming

- app/sequencescape/sequencescape/api/v2/well.rb
- app/views/exports/concentrations.csv.erb
- spec/factories/qc_result_factories.rb
- spec/views/exports/concentrations.csv.erb_spec.rb
- Units are expected to be in nM, wwe double check that
- We also add molarity to the key list
- Finally we avoid calling to_i, as we do NOT want to convert to a number
> Check units of concentration and do  not convert to int

- app/helpers/plate_helper.rb
- app/sequencescape/sequencescape/api/v2/well.rb
- spec/factories/plate_factories.rb
- spec/features/pooling_multiple_plates_spec.rb
- spec/features/viewing_a_minimal_plate_spec.rb
- spec/features/viewing_a_plate_spec.rb
This logic realy belongs at the front-end. But we can fix
that when we switch to pulling direct from Sequencescape
> Filter passed requests from pre-capture pooling

- app/models/sibling.rb
- app/views/tube_creation/final_tube.html.erb
Uncreated tubes don't have barcodes, this ensures
they display correctly.
> Tube preview displays uncreated tubes

- lib/deployed_version.rb
The rexep was returning strings for version numbers, which don't
respond to zero?
Two changes:
1) Consistently use strings for version numbering. Provides more
flexibility, especially for minor numbers. (Eg. allows for release
candidate markings)
2) Switch based on the presence of a release_hash
Rather than checking for the default 0.0.0 release, we just check if
we have a release hash at all.
> Fix deployed version with strings

- app/controllers/creation_controller.rb
We still need to fix the JS error handling, but this gives us server side logging of the issues.
> Log errors before returning

- .travis.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Our travis ci builds are breaking due to a mismatch between the chrome
version and chromedriver.
See equivalent fix in sequencescape for details.
> Add webdrivers to manage chrome-driver

- spec/features/creating_a_quadrant_stamp_primer_panel_plate_spec.rb
Required v1 API stub for plate lookup.
> Fix to failing test due to capybara update

- app/assets/javascripts/multi_plate_pooling.js
- app/assets/stylesheets/limber/screen.scss
- app/helpers/plate_helper.rb
- app/views/plates/show.json.erb
Pre-capture pools in the ISC pipeline were no-longer being sorted in
column order. This was causing delays in the lab. Pre-capture pooling
is a pooling step part way through the process, in which tagged samples
from the PCR-XP plate are pooled together prior to bait application.
While hashes in ruby are ordered based on insert order, there is no
such provision in javascript objects. Thus the browser does not have
to maintain key order when loading a JSON object. Indeed, it appears
that both chomium and firefox are sorting keys in alphabetical order.
In this case, the keys were the pre-cap pool ids.
This bug has been longstanding, but has mostly been hidden as the
pool-ids were typically generated in column order. In the plates that
were causing the problems, this was not the case. This …
> Fix limber isc sort bug

- bin/limber-dev
Fix limber-dev behaviour when an environment YAML file is not present
> Fix limber-dev

- app/helpers/plate_helper.rb
- spec/helpers/plate_helpers_spec.rb
Added sort on order id to pools helper method to order the pre-capture pools in the same order as on the manifest.
This commit fixes #302
> RT670996 Added sort on order id to pools helper method

- config/pipelines/bespoke_pcr.yml
Make the Hi-C library type available to go down the Bespoke PCR pipeline
> GPL-289 Hi-C library type (Limber half)

- app/sequencescape/sequencescape/api/v2/tube_rack.rb
Tube racks are a thing now in Sequencescape, and can come across
the API via their relationships with plates. (Or tubes)
> Add TubeRack resource

- config/purposes/heron.yml
Add label_template to heron purpose config, so that -QC label is printed out
- Also replace concentration file download in 'nM' with one in 'ng/ul'
> GPL-467 Limber changes for new quant type in Heron 96 pipeline

- app/models/labels/plate_split.rb
return an array - this was missed when converting qc_attributes to an array in this pull request - https://github.com/sanger/limber/pull/371/files?file-filters%5B%5D= (GPL-294)
> RT #690877 label printing bug

- config/pipelines/high_throughput_heron.yml
add these new library types to both branches of the pipeline, A and B
missed in https://github.com/sanger/limber/pull/450
> Fix for new library types GPL-494 and GPL-497

- config/pipelines/high_throughput_heron.yml
- config/pipelines/high_throughput_heron_384.yml
Hotfix
Hotfix addition of:
PCR with TruSeq tails amplicon
PCR with TruSeq tails amplicon 384
Added to Sequencescape in May, missed off limber config
> Add missing library types to limber pipelines

- app/models/concerns/presenters/statemachine/single_child_permissive.rb
- app/models/concerns/presenters/statemachine/state_allows_single_child_creation.rb
- app/models/presenters/plate_presenter.rb
- app/models/presenters/presenter.rb
- app/models/presenters/single_child_permissive_presenter.rb
- config/purposes/pWGS_384_bottom.yml
- spec/models/presenters/shared_labware_presenter_examples.rb
- spec/models/presenters/single_child_permissive_presenter_spec.rb
Add a SingleChildPermissivePresenter workflow: This gives the same behaviours per state as the PermissivePresenter, but with the added restriction that only a single child can be created for the labware (plate).
This is adopted, as per feedback from UAT, in the pWGS-384 pipeline where the End Prep and AL-Lib plates are created, started and passed in intertwined steps
PR directed at existing branch to better see the changes
> Gpl 679 single child presenter

- config/pipelines/high_throughput_heron_384_tailed.yml
- config/pipelines/high_throughput_heron_96_tailed.yml
Fixes #544
- Add Sanger_tailed_artic_v1_96 to high_throughput_heron_96_tailed
- Add Sanger_tailed_artic_v1_384 to high_throughput_heron_384_tailed
Closes #
*
*
* ...
> Add Sanger_tailed_artic_v1_xxx library types to pipelines

- app/sequencescape/sequencescape/api/v2/plate.rb
- spec/models/sequencescape_submission_spec.rb
- spec/sequencescape/api/v2/plate_spec.rb
Stock plate ordering was not specified, so was dependant on the
behaviour of the sequencescape database. This was resulting in
stock plates appearing to change.
This brings the behaviour mostly in line with Sequencescape, although
uses id over created at. This has the advantage of higher resolution,
quicker speed, and not needing a new sort scope added.
That said, we should probably make the same change within sequencescape.
Fixes #619
Closes #
*
*
* ...
> Apply sort order to stock plate retrieval

- app/sequencescape/sequencescape/api/v2/plate.rb
- spec/sequencescape/api/v2/plate_spec.rb
Closes #619
* The stock_plates method returns and array not a query object if the plate itself is a stock plate
* This doesn't respond to order
* But if we're a stock plate, we don't even need to build an array of ourself, just to extract us again.
Point 1 on this is a little painful, but probably better than the alternative of constructing a whole new API query just to retrieve something we already have.
> Fix stock plate lookup failure on stock_plates

- app/javascript/multi-stamp/components/MultiStamp.spec.js
- app/javascript/multi-stamp/components/MultiStamp.vue
- app/javascript/shared/transfersLayouts.js
Came out of UAT of GPL-851 'choose workflow' page handles characters from scanner badly.
Improves error message 'duplicated transfers' on quad stamp page, giving more information about the root cause of the problem.
R&D discussed whether the behaviour - where you can't process two active submissions in parallel - was OK, and concluded it was OK for now at least.
> Improve error message on quad stamp page

- app/models/asset_search_form.rb
- app/models/labware_creators/pooled_tubes_from_whole_tubes.rb
- app/models/ongoing_tube.rb
- app/sequencescape/sequencescape/api/v2/tube.rb
- app/views/sequencescape/api/v2/tubes/_tube.html.erb
- script/limber
- spec/features/pooling_multiple_tubes_into_one_tube_spec.rb
- spec/models/labware_creators/pooled_tubes_from_whole_tubes_spec.rb
The V1 API for tubes is incredibly slow, as it always renders the
full content of the tube. By contrast, V1 allows an utterly minimal
representation.
*Depends on* https://github.com/sanger/sequencescape/pull/3075
Closes #634
*
*
* ...
> Migrate tube lookup to V2 api

- app/assets/javascripts/tooltips.js
- app/assets/stylesheets/limber/colours.scss
- app/assets/stylesheets/limber/plate.scss
- app/assets/stylesheets/limber/screen.scss
- app/helpers/labware_helper.rb
- app/helpers/plate_helper.rb
- app/javascript/packs/application.js
- app/javascript/plain-javascript/quadrant-well-failing.js
- app/models/presenters/plate_presenter.rb
- app/sequencescape/sequencescape/api/v2/well.rb
- app/views/aliquots/_tagged_aliquot.html.erb
- app/views/aliquots/_well_failing_aliquot.html.erb
- app/views/application/_none.html.erb
- app/views/plates/_fail_wells.html.erb
- app/views/plates/_quadrant_helper.html.erb
- spec/features/failing_quadrants_spec.rb
- spec/helpers/labware_helper_spec.rb
- spec/support/feature_helpers.rb
Closes #649
* Negative control wells can't be failed individually
* Adds 'Select quadrant' helper buttons that *can* fail negative controls
* Adjust font sizes to ensure tags display correctly on 96 and 384 well plates
* Fail wells interface displays control state, to make it easier to understand why a well is not failable
* Fail wells interface displays well name as tooltip, as not really enough space on the well itself on 384 well plates.
> Issue649/gpl 901 restrict failing negative controls {heron}

- Gemfile.lock
All prior versions of mimemagic have been yanked due to a GPL license
violation. https://github.com/minad/mimemagic/tree/0.3.6
This updates the mimemagic version, allowing limber to build.
> Update yanked mimemagic version

- config/purposes/heron_lthr_384.yml
The TSsc384-PCR1-nCoV-2019/V4/B and TSsc384-PCR2-nCoV-2019/V4/B
templates have been added. This adds them to the whitelist.
Fixes #688
Closes #
*
*
* ...
> Add TSsc384-PCR?-nCoV-2019/V4/B templates

- .rubocop.yml
- app/controllers/creation_controller.rb
- app/controllers/pipelines_controller.rb
- app/controllers/plates_controller.rb
- app/models/concerns/presenters/creation_behaviour.rb
- app/models/concerns/presenters/extended_csv.rb
- app/models/concerns/presenters/statemachine.rb
- app/models/labels/plate_double_label_qc.rb
- app/models/labels/plate_label_lds_al_lib.rb
- app/models/labware_creators/custom_tagged_plate.rb
- app/models/labware_creators/multi_plate_pool.rb
- app/models/labware_creators/pooled_tubes_from_whole_plates.rb
- app/models/labware_creators/tube_from_tube.rb
- app/models/print_job.rb
- app/models/sequencescape_submission.rb
- app/models/utility/common_dilution_calculations.rb
- app/models/utility/concentration_binning_calculator.rb
- lib/purpose_config.rb
- lib/robot_configuration.rb
- script/limber
- spec/models/labware_creators/quadrant_split_plate_spec.rb
- spec/support/api_url_helper.rb
- spec/support/feature_helpers.rb
- spec/support/with_pmb_stubbed.rb
Adjust rubocop rules to treat hashes etc as single line.
> Exclude hashes and arrays from length cops

- app/models/presenters/qc_threshold_presenter.rb
- app/views/plates/_fail_wells.html.erb
- app/views/plates/_threshold.html.erb
- spec/models/presenters/qc_threshold_presenter_spec.rb
I also updated the appearance of the non-errored thresholds to be in green alerts to match the yellow ones used for when there are problems.  This makes it look much nicer.
> Fix thresholds for well failure to handle there being no results

- app/views/exports/cardinal_tagging_csv_for_custom_pooling.csv.erb
- spec/views/exports/cardinal_tagging_csv_for_custom_pooling.csv.erb_spec.rb
Closes #770 
The page works as is, if you upload a csv in the format described on the page.
The changes here are to alter the csv download on the previous plate page, to be in a format that matches the upload. See commit message for details.
> revert some of the features added to the download file in DPL-071

- app/models/labware_creators/multi_stamp_tubes.rb
Not sure if this was worth doing as DPL-074-1 (in progress) will be changing this bit of code, but UAT is currently broken so probably worth it to unblock that.
Need to reload the v2 plate to pull back the aliquots, as they are created during 'transfer_material_from_parent' - this means the submission will be created correctly - asset_groups was empty before
> DPL-154 fix (multiple studies)

- docs/creators.md
This is to prevent this file appearing every time you config:generate while Cardinal configuration is set as wip
> Update creators.md file

- config/pipelines/bespoke_pcr.yml
Closes https://github.com/sanger/sequencescape/issues/3416
Linked to Sequencescape PR sanger/sequencescape#3452
* Add emSEQ library type to the bespoke PCR pipeline.
> DPL-173: Add emSEQ library type

- app/models/concerns/presenters/statemachine/submission.rb
- spec/models/presenters/submission_plate_presenter_spec.rb
Closes #929 
**Fair warning!**  I haven't been able to test this on my local machine as I can't seem to get a plate in the correct state with all the submissions to match.  I have been able to confirm that it theoretically works with the unit tests, but we can check it on UAT with http://uat.limber.psd.sanger.ac.uk/limber_plates/1addaa80-573d-11ec-8a99-fa163e1e3ca9 once it's been deployed.
* Add submission creation to the sidebar of a submission plate if the previous submission became failed.
> DPL-187: New submission interface when submission failed

- config/purposes/heron_lthr_entry.yml
- docs/purposes_yaml_files.md
- spec/controllers/sequencescape_submissions_controller_spec.rb
Fixes #939
Omicron variant is resulting in dropouts, so primer panel changed
to reflect this.
Operational switch expected 10th January.
*
*
* ...
> Update primer panel used in submission [Do not release until 10th Jan]

- config/pipelines/high_throughput_targeted_nanoseq.yml
Targeted Nanoseq library type will be used for the first half of the pipeline, then Twist and Agilent types for ReISC.
> Config change after UAT.

- config/environments/development.rb
- lib/config_loader/base.rb
Make it possible to configure whether to deploy 'work in progress' .wip.yml files, to make it easier to deploy to UAT with them on, for example
> Configure whether to enable .wip.yml files

- app/javascript/shared/tubeTransferVolumes.js
- app/javascript/shared/tubeTransferVolumes.spec.js
- app/javascript/validate-paired-tubes/components/TransferVolumes.spec.js
- app/javascript/validate-paired-tubes/components/TransferVolumes.vue
Closes #961 
* Add a warning when the source concentration is lower than the target molarity.
I feel like I might have made a mistake getting this done in the calculated volume functions rather than just getting the Vue component to identify that the source molarity is lower than the target molarity, but actually I'm in two minds because it feels like logic the UI layer shouldn't need to deal with and this might be needed elsewhere as well without repeating the logic for when it applies.
> DPL-213 show low molarity transfer

- app/models/presenters/tube_presenter.rb
This line was causing the following exception:
- undefined method 'transfer_parameters' for {}:Hash
- when loading a tube page where the tube type wasn't known to Limber i.e. wasn't in a pipeline
I ran the Heron integration suite tests (heron_lthr_pipeline_spec), which passed
I noticed the exception locally, but also in frequent emails from prod.
> Fix exception when tube not known to Limber

- app/models/robots/bed/base.rb
- spec/models/robots/pooling_robot_spec.rb
- spec/models/robots/robot_spec.rb
We perform a last ditch validation on a bed before starting it.
Generally this should already have been gated by the previous step,
but if people use multiple tabs, manage to hit 'start robot' twice,
or something unexpected happens, we can hit here.
The previous error handling wasn't updated when the bed was migrated to
use the rails validation three years ago.
Closes #
*
*
* ...
> Fix rare error handling bug

- app/controllers/pipeline_work_in_progress_controller.rb
This comment is no longer correct, since the new request type does include the multiplexing step.
> Delete misleading comment

- app/views/labware/_content_header.html.erb
Previous commit (https://github.com/sanger/limber/pull/1071/commits/cf3370c1b76f7e08f4d1bfd9dded89a54980b693) wasn't effective because:
- the test selects elements with text 'Barcode' and adding 'Labware' on front doesn't exclude the element
- however, if we change the 'B' to lower case (which is also consistent with how the other fields on the page are formatted), it should work
> Int Suite test fix, take 2

- app/views/labware/_content_header.html.erb
Revert this back to just 'Barcode', as James has fixed the issue in the Integration Suite test
> Revert integration suite test fix

- config/robots.rb
Removes PhiX bed from robot bed verification configs until lab is ready for deployment.
> DPL-265 Removed PhiX bed from config until lab ready

- app/views/labware/_state_change.html.erb
a plate if there is a sequencing batch downstream
Closes #
*
*
* ...
> Add information note explaining that aliquots wont be removed on failing

- .github/workflows/ruby_test.yml
- app/controllers/pipeline_work_in_progress_controller.rb
- spec/controllers/pipeline_work_in_progress_controller_spec.rb
- spec/factories/labware_factories.rb
- spec/factories/plate_purpose_factories.rb
The final column needs to be pared down to only those labware where they have an ancestor with a purpose matching one of the earlier columns.
Closes #1221
> DPL-610: Add filter for the final column on work in progress views

- app/controllers/pipeline_work_in_progress_controller.rb
- app/views/pipeline_work_in_progress/show.html.erb
Closes #1220 
* Change work in progress views to show updated at times for labware rather than created at.
> Switch WIP views to use updated_at instead of created_at

- app/models/labware_creators/pooled_tubes_from_whole_plates.rb
- app/models/labware_creators/pooled_tubes_from_whole_tubes.rb
- app/models/labware_creators/stamped_plate_adding_randomised_controls.rb
- app/views/tube_creation/pooled_tubes_from_whole_plates.html.erb
- app/views/tube_creation/pooled_tubes_from_whole_tubes.html.erb
- config/purposes/bioscan.yml
- config/robots.rb
- docs/presenters.md
- spec/models/labware_creators/pooled_tubes_from_whole_plates_spec.rb
- spec/models/labware_creators/stamped_plate_adding_randomised_controls_spec.rb
- added Mosquito bed verification for PCR 2 step (it does move the yellow 'perform pcr' down so less visible)
- limited plate scan boxes to 1 on pooling into 384 tube
- changed PCR 1 step to also use the Limber PCR presenter so visibly you see the same screen for both PCR 1 and 2 steps
> Bioscan uat updates from testing 24th May

- config/purposes/bioscan.yml
Request to use Bioscan as Sequencescape Project name in production rather than BIOSCAN UK for flying insects
> Bioscan - change to project name

- app/models/labels/base.rb
- config/label_templates.yml
- lib/purpose_config.rb
Closes #
- Set label template options in label_templates.yml explicitly to fix heron 384-well plates label printing bug reported in RT 784533 .
> Set label template options to avoid using defaults

- app/models/print_job.rb
- config/sprint/label_templates/tube_label_traction_compatible.yml.erb
Closes #
- Sprint does not allow floats for positioning, i.e., x and y must be integers in label templates. Changed round label y position to an integer.
- Identified an issue in printing to squix using sprint, added comments, and created #1352 
> Bugfix bioscan tubes label printing

- app/views/exports/pbmc_bank_tubes_content_report.csv.erb
- spec/views/exports/pbmc_bank_tubes_content_report.csv.erb_spec.rb
Fix for bug whereby all rows are marked as 'contingency' in report, when some are sequencing tubes.
Purpose names were incorrect for the Bank tubes.
> scRNA - fix purpose names in report

- app/models/labware_creators/multi_stamp_tubes.rb
- app/models/presenters/submission_plate_presenter.rb
- app/models/sequencescape_submission.rb
- config/purposes/scrna_core_cell_extraction.wip.yml
- spec/models/labware_creators/multi_stamp_tubes_spec.rb
- spec/models/presenters/submission_plate_presenter_spec.rb
Closes #1386 
- Switch to controlling autodetection of studies and projects independently
- this requires an API change in Sequencescape, so is dependent on a new SS release
> DPL-911 correct study and project for cell extraction work

- app/javascript/multi-stamp-tubes/components/MultiStampTubes.vue
- app/javascript/multi-stamp-tubes/components/TubeArraySummary.spec.js
- app/javascript/multi-stamp-tubes/components/TubeArraySummary.vue
Closes #1436 
Adds a panel on the left of the screen under the plate view, to summarise the tube barcodes scanned on the right, including numbers of replicates
> DPL-962 added tube summary panel to tube arraying screen

- app/models/labels/tube_label_traction_compatible.rb
- config/purposes/bioscan.yml
- spec/models/labels/tube_label_traction_compatible_spec.rb
Closes #
- For `LBSN-384 PCR 1` and `LBSN-384 PCR 2` plates, show an`LBSN-96 Lysate` barcode in the top-right corner
- For `LBSN-384 PCR 2 Pool` tube, the first line shows the immediate parent `LBSN-384 PCR 2` plate barcode followed by well range extracted from `labware.name`
> Bioscan barcode label changes

- config/sprint/label_templates/tube_label_traction_compatible.yml.erb
Closes #
- Reduce the font size of the first line in Bioscan tube labels to avoid overflow.
> Bioscan tube labels first line

- config/robots.rb
Closes #1535 
Change bed number according to story
- bed 5 is at the front of the deck so is easier for the user to access for scanning
See also: https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/113/diffs 
Tested locally using integration suite.
> DPL-1042 Bed verification change (PBMC isolation)

- config/label_templates.yml
- config/purposes/scrna_core_cell_extraction.yml
- lib/purpose_config.rb
Closes #1536 
Create a 'plate_a' label template and use it in the purpose config for LRC Blood Aliquot
- this solution seems to work (printers drop down changes in the UI), but I'm not sure it's a good solution - may refactor
> DPL-1043 Change label type for 'LRC Blood Aliquot' to plate

- app/javascript/asset-comments/components/AssetComments.spec.js
- babel.config.js
- package.json
- yarn.lock
Closes #
- Match vue and vue-template-compiler versions (2.6.11)
- Change proposal plugins to transform plugins in babel config
- Rebuild yarn lockfile
> Update babel to version 7.23.9

- config/purposes/scrna_core_cdna_prep.wip.yml
Main changes for this story are in Sequencescape - https://github.com/sanger/sequencescape/pull/4017
- LRC PBMC Pools Input must be a 'stock plate' so that it can be used in sample manifests in Sequencescape
> DPL-823 Import PBMC pool plates into Sequencescape

- app/controllers/exports_controller.rb
- config/exports/exports.yml
- spec/controllers/exports_controller_spec.rb
- spec/fixtures/app/views/exports/multiple_ancestor_plates.csv.erb
- spec/fixtures/config/exports/multiple_ancestor_plates.yml
- spec/lib/config_loader/exports_loader_spec.rb
Closes #
Updates for using multiple ancestor plates in driver file download
Summary:
The ancestor_purpose setting of an export configuration will make an additional controller instance variable`@ancestor_plate_list` populated with all ancestor plates of that purpose and available in the view template.
Background:
The existing export controller allows making an ancestor plate available to the export view template by specifying the ancestor plate purpose in the export configuration. This is useful in several cases, for example, access to parent plate barcode and relating source wells specified in transfer templates in driver file exports. However, only one ancestor plate is made available to the view, the first, which assumes a single parent for the current plate being viewed and download …
> DPL-1024-2 PBMC donor pooling - ancestor plates

- app/models/concerns/labware_creators/donor_pooling_validator.rb
- app/models/labware_creators/donor_pooling_plate.rb
- app/views/plate_creation/donor_pooling_plate.html.erb
- config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml
- spec/lib/config_loader/poolings_loader_spec.rb
- spec/models/labware_creators/donor_pooling_spec.rb
Closes #
- Add a validation into LCR PBMC Pools plate creation to enforce cell count data presence on the LRC PBMC Defrost PBS wells going into pooling. All wells must have cell count data unless they are failed. This will ensure consistency between the created pools plate and the driver download.
- Use lowercase letters for  `request_type_key` for `limber_scrna_core_cdna_prep` in pipeline config to make the _Add and empty LRC HT 5p Chip plate_ button available.
> DPL-916-4 PBMC donor pooling - validate cell count

- spec/models/labels/plate_label_human_barcode_spec.rb
Closes N/A
- Added a test for the human readable barcode label class (See [main change](https://github.com/sanger/limber/pull/1742))
> Y24-096 - Added 2D barcodes to LRC Blood Aliquot labels [2]

- spec/models/labels/plate_label_cellaca_qc_spec.rb
- spec/models/labels/plate_label_quad_qc_spec.rb
This change is causing CI issues currently.
See: https://github.com/sanger/limber/actions/runs/9744623445/job/26890652637
- Updates plate_label_cellaca_qc_spec to match label date with a date regex keeping it inline with other specs
> Test fix cellaca plate label date test

- app/controllers/concerns/exports_filename_behaviour.rb
- app/controllers/exports_controller.rb
- app/controllers/tubes/tubes_exports_controller.rb
- config/exports/exports.yml
- docs/exports_yaml_files.md
- spec/controllers/concerns/exports_filename_behaviour_spec.rb
Closes #1521 
- Extends exports.yml documentation
- Adds ability to specify independent filename for exports
- Adds ability to prepend barcodes in exports filename
- Adds ability to include parent labware barcode in exports filename
There are no independent unit tests, mainly because the exports_controller tests it by proxy and it is has a different style of testing. But I have tested manually with a few variations and it is working.
> DPL-1031 - File name improvements

- .gitignore
- app/helpers/barcode_labels_helper.rb
- app/models/presenters/presenter.rb
- app/sequencescape/sequencescape/api/v2/submission_template.rb
- app/sequencescape/sequencescape/api/v2/transfer_template.rb
- app/sequencescape/sequencescape/api/v2/tube_purpose.rb
- lib/purpose_config.rb
- lib/tasks/config.rake
- spec/data/settings.yml
Closes #1794 
- Use new V2 endpoints for operations during `config:generate`.
- Still to do:  Remove the searches config population, but these are still used throughout the application and I want to confirm they are no longer needed before creating a new endpoint unnecessarily.
> Y24-190-1: Update config generate to SS API v2

- app/javascript/multi-stamp/components/PrimerPanelFilter.spec.js
- app/javascript/shared/wellHelpers.js
- app/javascript/shared/wellHelpers.spec.js
- app/models/state_changers.rb
- app/sequencescape/sequencescape/api/v2/shared/has_requests.rb
- config/purposes/scrna_core_cdna_prep.wip.yml
- spec/models/state_changers_spec.rb
2 fixes based on UAT testing:
1. Fix automatic state change on LRC GEM-X 5p cDNA PCR XP plate
- It wasn't completing the requests when coming down the SeqOps cDNA Prep route
- It only worked for the Faculty input route
- This is because the only request type specified in the 'work_completion_request_type' config was 'limber_scrna_core_cdna_prep_input'
- Had to enhance the AutomaticStateChange functionality to allow multiple request types
2. De-duplicate requests in the requestsForWell function
- in the aggregation pipeline for scRNA Core, the plates that the submission is done on may contain multiple aliquots
- if this is the case, each aliquot in the well references the same request
- this method was pulling the request from each of the aliquots - presumably with the assumption that each …
> Fix automatic state change on LRC GEM-X 5p cDNA PCR XP plate

- lib/purpose_config.rb
Closes #
- Fixes issue when running config generate task
- error was 'undefined method fetch for nil:NilClass'
- because 'options' variable was being redefined
- changing the name of the variable works
- Bit of extra refactoring to make distinction between local and instance variables clearer
> Fix: config:generate error

- config/robots.rb
Closes #
- They will no longer be pooling using the STARlet so we only need the bed verification Robot Option 1 for the STAR.
See associated Integration Suite PR here - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/147/diffs 
> DPL-1025 amendment - remove bed verification

- app/views/exports/hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools.csv.erb
- spec/views/exports/hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools.csv.erb_spec.rb
Closes #
- Add blank line into hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools file, to be consistent with other files in the same pipeline
See file in bold below, in context of all the other files in the pipeline. Everything in the cell extraction and cDNA prep stages has a blank second line, while everything in the library prep stage doesn't. 
We decided to change hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools to make it consistent with its surroundings. 
The library prep files are left as-is, because the library prep stage will use the existing robot methods set up for the existing bespoke chromium pipelines - so if we change the driver files, it will create work for R&D.
Purpose | export file | Blank second line or not?
-- | -- | --
LRC Blood Bank | …
> Add blank line into robot driver file, for consistency

- app/models/labware_creators/base.rb
- app/models/labware_creators/final_tube.rb
- app/models/labware_creators/final_tube_from_plate.rb
- app/models/labware_creators/plate_with_template.rb
- app/models/labware_creators/pooled_tubes_from_whole_plates.rb
- app/models/labware_creators/tube_from_tube.rb
- app/sequencescape/sequencescape/api/v2/transfer.rb
- spec/factories/transfer_factories.rb
- spec/features/creating_a_tag_plate_spec.rb
- spec/features/pool_tubes_at_end_of_pipeline_spec.rb
- spec/features/pooling_multiple_plates_into_one_tube_spec.rb
- spec/models/labware_creators/base_spec.rb
- spec/models/labware_creators/custom_tagged_plate_spec.rb
- spec/models/labware_creators/final_tube_from_plate_spec.rb
- spec/models/labware_creators/final_tube_spec.rb
- spec/models/labware_creators/plate_with_template_spec.rb
- spec/models/labware_creators/pooled_tubes_from_whole_plates_spec.rb
- spec/models/labware_creators/tagged_plate_spec.rb
- spec/models/labware_creators/tube_from_tube_spec.rb
- spec/spec_helper.rb
- spec/support/api_url_helper.rb
- spec/support/shared_tagging_examples.rb
Closes #1818 
- Switch over to using V2 transfers.
We no longer have to get the template from the API before we request to create the transfer since we pass the UUID to the template endpoint to create a transfer.  We already have the UUIDs in the app config from the `config:generate` rake task.
> Y24-190-3: Use v2 transfers and transfer templates

- app/controllers/plates_controller.rb
- app/models/concerns/labware_creators/tagged_plate_behaviour.rb
- app/models/labware_creators/final_tube_from_plate.rb
- app/models/state_changers.rb
- app/sequencescape/sequencescape/api/v2/state_change.rb
- spec/controllers/plates_controller_spec.rb
- spec/controllers/robots_controller_spec.rb
- spec/controllers/tubes_controller_spec.rb
- spec/features/cancelling_a_whole_plate_spec.rb
- spec/features/creating_a_tag_plate_spec.rb
- spec/features/failing_a_whole_plate_spec.rb
- spec/features/failing_quadrants_spec.rb
- spec/features/failing_thresholds_spec.rb
- spec/features/failing_wells_spec.rb
- spec/features/plate_transfer_spec.rb
- spec/models/labware_creators/custom_tagged_plate_spec.rb
- spec/models/labware_creators/final_tube_from_plate_spec.rb
- spec/models/labware_creators/tagged_plate_spec.rb
- spec/models/robots/plate_to_tube_racks_robot_spec.rb
- spec/models/robots/pooling_and_splitting_robot_spec.rb
- spec/models/robots/pooling_robot_spec.rb
- spec/models/robots/quadrant_robot_spec.rb
- spec/models/robots/robot_spec.rb
- spec/models/robots/splitting_robot_spec.rb
- spec/models/state_changers_spec.rb
- spec/support/shared_tagging_examples.rb
Closes #1818 
- Create new StateChanges with the API v2 endpoint on Sequencescape.
- Update tests to match expected calls.
> Y24-190-3: Use API v2 StateChange resource

- app/frontend/javascript/multi-stamp-tubes/components/MultiStampTubes.spec.js
- app/frontend/javascript/multi-stamp-tubes/components/MultiStampTubes.vue
- app/frontend/javascript/multi-stamp-tubes/components/filterProps.js
- app/frontend/javascript/shared/components/LabwareScan.spec.js
- app/frontend/javascript/shared/components/LabwareScan.vue
- app/frontend/javascript/shared/components/tubeScanValidators.js
- app/frontend/javascript/shared/components/tubeScanValidators.spec.js
- app/frontend/javascript/shared/resources.js
- app/models/labware_creators/multi_stamp_tubes.rb
- app/views/plate_creation/multi_stamp_tubes.html.erb
- config/purposes/scrna_core_cell_extraction.yml
Closes #1501 
- Adds acceptablePurposes to MultiStampTubes component to enable pipeline specific purpose restriction.
- Adds checkAcceptablePurposes validator to tubeScanValidators.
- Enforces 'LRC Blood Aliquot' purpose type for scRNA core sample arraying.
I have tested this against both the scrna and cardinal int suite and it works as expected
> DPL-1023 - Sample arraying restrict tube type

- app/frontend/javascript/labware-custom-metadata/components/LabwareCustomMetadataAddForm.spec.js
- app/frontend/javascript/multi-stamp-tubes/components/MultiStampTubes.vue
- app/frontend/javascript/shared/components/LabwareScan.spec.js
- app/frontend/javascript/shared/components/Plate.spec.js
- app/frontend/javascript/shared/components/Well.spec.js
- app/frontend/javascript/shared/components/Well.vue
- package.json
- vite.config.mjs
- yarn.lock
`yarn test` was outputting a large amount of logs and errors. This PR attempts to _nicely_ clean them up.
- Bumps vue test utils version.
- Adds console suppression for `Download the Vue Devtools extension` warning.
- This is probably something to do with not setting the correct Vue environment for testing but Limber has Vue instances all over the place so I am not sure of a way to configure this.
- Suppresses devour console logs where appropriate.
- Implements `[BootstrapVue warn]: tooltip - The provided target is no valid HTML element.` workaround fix.
- Fixes test data using Well.vue without colour_index prop causing console warnings.
> Fix yarn test output

- codecov.yml
Closes https://github.com/sanger/limber/issues/1801
- Removed 'ignore' vue files section in codecov.yml 
With the addition of `"coverageProvider": "v8"` to vite.config.mjs, the Vue SFC code coverage is now working as expected.
> Y24-207: fix incorrect test coverage for Vue SFC components

- config/pipelines/bespoke_pcr.yml
Fix for RT issue pointing out SGE library type wasn't working to show next steps in Limber.
> FIX - added SGE library type to bespoke pcr pipeline

- config/robots.rb
Closes #
- Bed number change requested by Abby in Slack:
> We have recently made a change to the pooling protocol that requires the bed verification of the LRC PBMC Pools plate to move from bed 14 to bed 13.
Please would you be able to amend this when you have time?
Goes with Integration Suite PR - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/164/diffs
Have run Int Suite scRNA Core test locally, but no other Int Suite tests.
> Bed number change requested by Abby in Slack

- config/purposes/lcm_triomics.wip.yml
Closes #
- Add additional tag layout templates to the LCMT EM Lib PCR config. The names come from email conversations.
> Add TSISC_UDI96 and TSRNAhWGS_UDI96 to LCMT EM Lib PCR config

- .pryrc
- app/frontend/javascript/custom-tagged-plate/components/CustomTaggedPlate.spec.js
- app/frontend/javascript/custom-tagged-plate/components/CustomTaggedPlate.vue
- app/models/labware_creators/custom_tagged_plate.rb
- app/sequencescape/sequencescape/api/v2/tag_layout.rb
- spec/models/labware_creators/custom_tagged_plate_spec.rb
Closes #1818 
- Use new endpoint for TagLayout.
- Use the custom method for TagLayoutTemplate to create a TagLayout.
> Y24-190-3 Use API v2 TagLayout

- app/models/labware_creators/custom_tagged_plate.rb
- app/models/labware_creators/merged_plate.rb
- app/models/labware_creators/multi_plate_pool.rb
- app/models/labware_creators/multi_stamp.rb
- app/models/labware_creators/multi_stamp_tubes.rb
- app/models/labware_creators/multi_stamp_tubes_using_tube_rack_scan.rb
- app/sequencescape/sequencescape/api/v2/pooled_plate_creation.rb
- spec/features/pooling_multiple_plates_spec.rb
- spec/models/labware_creators/custom_tagged_plate_spec.rb
- spec/models/labware_creators/merged_plate_spec.rb
- spec/models/labware_creators/multi_plate_pool_spec.rb
- spec/models/labware_creators/multi_stamp_spec.rb
- spec/models/labware_creators/multi_stamp_tubes_spec.rb
- spec/models/labware_creators/multi_stamp_tubes_using_tube_rack_scan_spec.rb
- spec/models/labware_creators/quadrant_stamp_primer_panel_spec.rb
Closes #1818 
- Make use of the new PooledPlateCreations endpoint in Sequencescape.
- Add tests to ensure these are working as expected.
> Y24-190-3: Use API v2 endpoint for PooledPlateCreations

- app/views/exports/hamilton_gem_x_5p_chip_loading.csv.erb
- spec/views/exports/hamilton_gem_x_5p_chip_loading.csv.erb_spec.rb
Closes https://github.com/sanger/limber/issues/1779
- Adds Source well volume, Sample volume and PBS volume columns in the driver files for PBMC Pools (or Input) plate to GEM-X 5p transfer 
> Y24-193 add volume columns to driver file for PMBC pools to GEM-X 5p chip

- app/views/exports/hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools.csv.erb
- spec/views/exports/hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools.csv.erb_spec.rb
Additional tweaks on top of https://github.com/sanger/limber/issues/1914
Requirements from slack:
- "we want to cap the minimum vol to take at 5ul"
- "we don't need this (vol) or the resuspension vol to 2 decimal places, 1 is fine."
- Updates `hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools` to reflect the above requirements.
> Y24-319-1 - Additional pooling driver file adjustments.

- app/models/print_job.rb
- spec/models/print_job_spec.rb
Closes #1880 
The exact cause and fix is further documented in the linked issue above.
- Updates print_job to safely handle the case where label_template_id does not exist.
- Fixes incorrect print_job 'pmb is down' tests.
> Y24-287 - Print job exception

- config/purposes/scrna_core_cdna_prep.yml
- config/purposes/scrna_core_cell_extraction.yml
LRC PBMC Defrost PBS total cell count/ml defaults to 500000 
LRC PBMC Bank defaults to  85%
> DPL-918 extra setting

- app/models/labware_creators/pooled_tubes_from_whole_tubes.rb
- app/models/labware_creators/tube_from_tube.rb
- app/sequencescape/sequencescape/api/v2/tube_from_tube_creation.rb
- spec/features/pooling_multiple_tubes_into_one_tube_spec.rb
- spec/models/labware_creators/pooled_tubes_from_whole_tubes_spec.rb
- spec/models/labware_creators/tube_from_tube_spec.rb
- spec/support/api_url_helper.rb
Closes https://github.com/sanger/limber/issues/1818
- Use `tube_from_tube_creation` endpoint from SS API v2.
- Update tests to match the expectations of method calls.
> Y24-190-3: Use API v2 TubeFromTubeCreation endpoint

- config/pipelines/bespoke_pcr.yml
- config/purposes/bespoke.yml
Reverts sanger/limber#1988 because there're some additional changes to be made.
> Revert "Adding Norm plate after LBB Lib PCR-XP for tracking Beckman normalisation"

- config/pipelines/high_throughput_rvi_bcl.yml
Closes #1615 
- Adds limber_reisc request type to possible rvi bcl pipeline request keys.
Related Sequencescape PR: https://github.com/sanger/sequencescape/pull/4468
> Y24-014 - Ability to re-run RVI BCL pipeline

- app/models/labware_creators/baited_plate.rb
- spec/factories/bait_library_layout_factories.rb
- Fixes regression from bait library preview v2 api where layout was returned instead of well_layout causing the bait library layout preview page to show no baits despite baits being present.
Linked Sequencescape PR: https://github.com/sanger/sequencescape/pull/4478
There is also an integration suite PR.
> Bait Library Layout Preview fix 

- config/robots.rb
Closes #
Requirements from Abby in Slack following end to end lab test:
For bed verification, 2 bed changes:
- For the LRC PBMC Pools => LRC GEM-X 5p Chip, please could the LRC PBMC Pools plate be moved to bed 5
- For the LRC GEM-X 5p Chip => LRC GEM-X 5p GEMS, please could the LRC GEM-X 5p GEMS plate be moved to bed 4
Need to add a corresponding Int Suite PR.
> Customer-requested bed number change

- config/robots.rb
Closes #
This PR covers the minor changes that can be done quickly after UAT feedback and discussions that are available at https://github.com/sanger/limber/issues/1782#issuecomment-2468324507 . 
- Feedback Item (2) Rename robot config to Bravo LCMT EMSeq Verify Initial Setup
- Feedback Item (4) Remove robot config Bravo LCMT DNA Adp Lig Verification
- Feedback Item (5) Swap beds in robot config Bravo LCMT DNA Adp Lig => LCMT DNA Lib PCR
- Feedback Item (6) Remove robot config Bravo LCMT EM TET2 Stop Verification
- Feedback Item (8) Change position for LCMT EM APOBEC Deam to (4,3) in robot config Bravo LCMT EM TET2 Stop to Denat and Deam Setup
- Feedback Item (9) Remove robot config Bravo LCMT EM APOBEC Deam Verification
_[Feature Branches] - …
> Y24-198 UAT Updates LCM Triomics bed verifications

- app/sequencescape/sequencescape/api/v2/shared/has_poly_metadata.rb
Closes #
- Ensure the helper method returns a single PolyMetadatum object instead of array; use detect instead of find.
> Fix poly metadatum by key for chip loading driver

- config/purposes/scrna_core_library_prep.yml
Closes #
Also see Integration Suite PR - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/208/diffs 
- Change the diluent volume, as requested by lab staff
- Changes to the binning ranges - requirement missed back in June
> Y25-012 - Changes to scRNA Core binning rules

- app/controllers/tag_plates_controller.rb
- app/models/presenters/qcable_presenter.rb
- app/sequencescape/sequencescape/api/v2/lot.rb
- app/sequencescape/sequencescape/api/v2/lot_type.rb
- app/sequencescape/sequencescape/api/v2/purpose.rb
- app/sequencescape/sequencescape/api/v2/qcable.rb
- spec/factories/qcable_factories.rb
- spec/features/creating_a_tag_plate_spec.rb
- spec/support/api_url_helper.rb
Closes https://github.com/sanger/limber/issues/1818
- Pull Qcables from Sequencescape API v2.
- Change which attributes we extract from the Qcable to align with V2 API usage.
- Update tests to match.
> Y24-190: Use SS API V2 for Qcable resources

- config/pipelines/high_throughput_lcmb.yml
- config/purposes/lcmb.yml
Closes #1656 
- Changed the purpose name for `Custom Pool Norm` to `Custom Norm` so it can fit on labels.
- `Custom Pool` has not been changed.
> Y24-038 - Changed "Custom Pool Norm" to "Custom Norm" in purposes

- app/controllers/labware_controller.rb
Fixes:
A follow-on from #2044
- Removes rescue for non-existent error type.
> Remove StateChangeError rescue block

- app/controllers/tube_racks/tube_racks_exports_controller.rb
- app/sequencescape/sequencescape/api/v2/tube.rb
- app/sequencescape/sequencescape/api/v2/tube_rack.rb
- app/views/exports/hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare.csv.erb
- app/views/tube_racks/tube_racks_exports/hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare.csv.erb
- config/exports/exports.yml
- config/purposes/scrna_core_cell_extraction.yml
- spec/controllers/tube_racks/tube_racks_exports_controller_spec.rb
- spec/factories/tube_factories.rb
- spec/factories/tube_rack_factories.rb
- spec/views/exports/hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare.csv.erb_spec.rb
- spec/views/tube_racks/tube_racks_exports/hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare.csv.erb_spec.rb
Closes #2070 
- Updates `hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare` driver file to use tube racks.
- Linked Sequencescape PR: https://github.com/sanger/sequencescape/pull/4675
- Linked Integration Suite PR: https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/218
> Y24-456 - Tube racks driver file

- .github/workflows/test_ruby.yml
- README.md
- spec/spec_helper.rb
Changes proposed in this pull request
- Adds '--no-sandbox' flag to chromedriver
- Sets chrome to older version for CI.
- https://github.com/teamcapybara/capybara/issues/2800
> Y25-186 - RSpec feature CI test fixes

- config/pipelines/high_throughput_bge.wip.yml
Changed request type names to BGE specific ones to allow creation of BGE multiplexing tubes.
> Changed request type names to match sequencescape changes

- .github/workflows/test_js.yml
- .github/workflows/test_ruby.yml
Closes #2216 
- Migrated setup steps to use the composite actions
- Migrated testing and coverage steps to use the composite actions
- Removed code climate action (we no longer use code climate)
- Improved naming and separation of the testing jobs
- Minor improvements to syntax and structure
While there aren't any new steps for these workflows, a backwards compatible change has been made to the code coverage action [here](https://github.com/sanger/.github/pull/28).
> Y25-107-4 - Migrate & Improve testing workflows

- config/purposes/bge.wip.yml
Closes #
- Review BGE TODO comments and remove them.
- For BGE Lib, use the tag layout template `IDT for Illumina UDI v2` only. 
Confirmed by email. Subject: RE: Acceptable Tag Layout Templates for, From: Jamie, Date: 11 June 2025
> Y25-226 [PR] creating bge lib prepool after wells on bge lib pcr xp failed
